{
 "title": "Study dashboard v2.01",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  {
   "title": "핵심 비즈니스 메트릭 지표",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "대시보드 조회 지표",
   "type": "stat",
   "description": "최대 조회 시간 (1-3 분 사이의 최대 조회 시간을 가져옴)\n평균 실행 시간 (전체 실행 시간의 합 / 전체 실행 횟수)",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dashboard_get_seconds_max{method=\"getDashboard\", instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "최대 조회 시간"
    },
    {
     "expr": "increase(dashboard_get_seconds_sum{method=\"getDashboard\", instance=\"$instance\", application=\"$application\"}[1m]) / increase(dashboard_get_seconds_count{method=\"getDashboard\", instance=\"$instance\", application=\"$application\"}[1m])",
     "legendFormat": "평균 실행 시간"
    }
   ]
  },
  {
   "title": "대시보드 최대 조회 시간 (그래프)",
   "type": "timeseries",
   "description": "추이를 알아보기 위함",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "dashboard_get_seconds_max{method=\"getDashboard\", instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "회원 그룹 가입 지표",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (instance, application) (\n  increase(join_request_total{method=\"sendJoinRequest\", instance=\"$instance\", application=\"$application\"}[1m])\n)",
     "legendFormat": "전체 가입 요청"
    },
    {
     "expr": "sum by (instance, application) (\n  increase(join_request_total{method=\"acceptJoinRequest\", instance=\"$instance\", application=\"$application\"}[1m])\n)",
     "legendFormat": "가입 요청 수락"
    },
    {
     "expr": "sum by (instance, application) (\n  increase(join_request_total{method=\"sendJoinRequest\", instance=\"$instance\", application=\"$application\"}[1m])\n) - \nsum by (instance, application) (\n  increase(join_request_total{method=\"acceptJoinRequest\", instance=\"$instance\", application=\"$application\"}[1m])\n)",
     "legendFormat": "가입 요청 거절 수"
    },
    {
     "expr": "sum by (instance, application) (\n  increase(join_request_total{method=\"joinGroup\", instance=\"$instance\", application=\"$application\"}[1m])\n)",
     "legendFormat": "멘토링 가입 요청 수"
    }
   ]
  },
  {
   "title": "분당 그룹 생성 수",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "increase(group_create_total{method=\"createGroup\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "기본", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "서버 지속 시간",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "서버 재시작 시간",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "힙 메모리 사용량",
   "type": "stat",
   "description": "메모리 누수 / GC 빈도를 파악할 때 사용 \n여기서 오류가 난다 -> GC가 안 되게 데이터가 계속 누적이 될 때 발생하는...\n서버 한 대씩 내렸다가 다시 올리면서 원인 파악 해야 함...\n",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap 사용량",
   "type": "stat",
   "description": "과도하면 로딩 문제나 컴파일 오버헤드를 의심할 수 있음",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "시스템 부하 평균",
   "type": "timeseries",
   "description": "운영 체제(OS)의 시스템 부하 평균을 지난 1분 동안 평균한 메트릭으로, CPU나 다른 리소스를 기다리는 프로세스 수를 나타내는 지표",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "평균 부하 [1m]"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "CPU 코어 크기"
    }
   ]
  },
  {
   "title": "CPU 사용량",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "시스템 CPU 사용량"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "프로세스 CPU 사용량"
    }
   ]
  },
  { "title": "HikariCP 지표", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "커넥션 풀 사이즈",
   "type": "stat",
   "description": "기본 10\n",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "커넥션 사용 가능 수 확인 \n대기 생기면 쿼리 응답이 너무 오래 걸리는 것 < 이런 경우 체크해 봐야 한다",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "사용 중"
    },
    {
     "expr": "hikaricp_connections_idle{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "사용 가능"
    },
    {
     "expr": "hikaricp_connections_pending{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "대기"
    }
   ]
  },
  {
   "title": "커넥션 타임아웃 수",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Creation Time"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Usage Time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Acquire Time"
    }
   ]
  },
  { "title": "Tomcat 지표", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "톰캣 최대 스레드 수",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_threads_config_max_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Max threads"
    }
   ]
  },
  {
   "title": "HTTP Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[1m]))",
     "legendFormat": "5xx - Server Errors"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"4..\"}[1m]))",
     "legendFormat": "4xx - Client Errors"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"2..\"}[1m]))",
     "legendFormat": "2xx - Success"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"3..\"}[1m]))",
     "legendFormat": "3xx - Redirections"
    }
   ]
  },
  {
   "title": "초당 요청 수",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_threads_current_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "전체 스레드 개수"
    },
    {
     "expr": "tomcat_threads_busy_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "실제 동작 스레드"
    }
   ]
  },
  {
   "title": "API 요청 TOP 10",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "전체 스레드 (200)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  { "title": "Logback 지표", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "INFO logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"info\"}[5m])",
     "legendFormat": "info",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"error\"}[5m])",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"warn\"}[5m])",
     "legendFormat": "warn",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DEBUG logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"debug\"}[5m])",
     "legendFormat": "debug",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "TRACE logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"trace\"}[5m])",
     "legendFormat": "trace",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}